import os

KEYCLOAK_URL: str = os.getenv('KEYCLOAK_URL')
KEYCLOAK_REALM_NAME: str = os.getenv('KEYCLOAK_REALM_NAME')
KEYCLOAK_CLIENT_ID: str = os.getenv('KEYCLOAK_CLIENT_ID')
KEYCLOAK_CLIENT_SECRET: str = os.getenv('KEYCLOAK_CLIENT_SECRET')
